### ISSUE TITLE
CDC User stories for Selenium tests

### ISSUE THREAD

**Issue by MortenSikt** [cessda/cessda.cdc.versions#571]
- [ ] 1.	[User is interested in finding all studies based on a free text search, for instance “Social media”](https://github.com/cessda/cessda.cdc.versions/issues/572)
- [ ] 2.	[User is interested in finding all studies based on a CESSDA Topic classification](https://github.com/cessda/cessda.cdc.versions/issues/578)
- [ ] 3.	[User is interested in finding all studies based on a free text search, within a specific collection year period](https://github.com/cessda/cessda.cdc.versions/issues/581)
- [ ] 4.	[User is interested in finding all studies based on a CESSDA Topic classification, within a specific collection year period](https://github.com/cessda/cessda.cdc.versions/issues/582)
- [ ] 5.	[User is interested in finding all studies based on a free text search, within a specific collection year period, from a specific country](https://github.com/cessda/cessda.cdc.versions/issues/583)
- [ ] 6.	[User is interested in finding all studies based on a CESSDA Topic classification, within a specific collection year period, from a specific country](https://github.com/cessda/cessda.cdc.versions/issues/584)
- [ ] 7.	[SP user is interested in finding a specific study from their catalogue in the CDC](https://github.com/cessda/cessda.cdc.versions/issues/585)
- [ ] 8.	[User is interested in identifying how many studies exist for a specific language](https://github.com/cessda/cessda.cdc.versions/issues/586)
- [ ] 9.	[User is interested in finding all studies for a specific language based on a free text search, for instance “réseaux sociaux“](https://github.com/cessda/cessda.cdc.versions/issues/587)
- [ ] 10.	[User is interested in finding all studies for a specific language based on a CESSDA Topic classification](https://github.com/cessda/cessda.cdc.versions/issues/588)
- [ ] 11.	[After finding a specific study in the result list, user wants to “read more”](https://github.com/cessda/cessda.cdc.versions/issues/589)
- [ ] 12.	[After finding a specific study in the result list, user wants to read everything about the study](https://github.com/cessda/cessda.cdc.versions/issues/590)
- [ ] 13.	[After finding a specific study in the result list, user wants to access data](https://github.com/cessda/cessda.cdc.versions/issues/591)
- [ ] 14.	[After finding a specific study, user is interested in reading about the similar results](https://github.com/cessda/cessda.cdc.versions/issues/592)
- [ ] 15.	[After finding a specific study, user is interested in accessing the study](https://github.com/cessda/cessda.cdc.versions/issues/580)
- [ ] 16.	[After finding a specific study, user is interested in in finding other studies with same topic/keywords](https://github.com/cessda/cessda.cdc.versions/issues/579)
- [ ] 17.	[User is interested in sorting the result list based on newest publication](https://github.com/cessda/cessda.cdc.versions/issues/577)
- [ ] 18.	[User is interested in sorting the result list based on newest collection](https://github.com/cessda/cessda.cdc.versions/issues/576)
- [ ] 19.	[User is interested in accessing the User Guide to learn more about how one can search in the CDC](https://github.com/cessda/cessda.cdc.versions/issues/575)
- [ ] 20.	[User is interested in reading more about the CDC](https://github.com/cessda/cessda.cdc.versions/issues/574)
- [ ] 21.	[User is interested in learning more about the REST API](https://github.com/cessda/cessda.cdc.versions/issues/573)
